import { Component } from '@angular/core';
import { ButtonComponent } from '../../components/button/button.component';
import { DescriptionComponent } from '../../components/description/description.component';
import { HeroComponent } from '../../components/hero/hero.component';
import { InverteddescriptionComponent } from '../../components/inverteddescription/inverteddescription.component';
import { OfferingsComponent } from '../../components/offerings/offerings.component';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [
    ButtonComponent,
    HeroComponent,
    DescriptionComponent,
    InverteddescriptionComponent,
    OfferingsComponent
  ],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {
  title = 'In “About the School”';
  description = 'The School of Art is founded on the belief that art is a fundamental force in national and international culture, and that one of the primary standards by which societies are judged is the quality, creative freedom, critical insight, and formal and technical innovation of the visual art they produce. The Yale School of Art teaches at the graduate and undergraduate levels, and consequently the student body consists of those whose primary or exclusive focus is art as well as those for whom art is an essential part of a varied course of inquiry. The school currently offers degrees and undergraduate majors in the areas of graphic design, painting/printmaking, photography, and sculpture.';
  heroUrl = "https://cdn.filestackcontent.com/output=format:jpg/kU6CuhxfT9GiDqPEBAem";

  invertedTitle = "The Yale School of Art is a graduate school that confers Master of Fine Arts Degrees in Graphic Design, Painting/Printmaking, Photography, and Sculpture";
  invertedDesc = "Artists and designers of unusual promise and strong motivation are provided an educational context in which they can explore the potential of their own talents in the midst of an intense critical dialogue. This dialogue is generated by their peers, by distinguished visitors, and by a faculty comprised of professional artists of acknowledged accomplishment.The graduate student’s primary educational experience at Yale is centered on the student’s own studio activity. Supporting this enterprise are the experience, knowledge, and skills gained from rigorous, structured courses such as drawing, filmmaking, the relativity of color, and the rich academic offerings found throughout Yale. Each student is routinely exposed to many aesthetic positions through encounters with faculty members and visitors. The School is devoted not only to the refinement of visual skills, but also to the cultivation of the mind. Students must bring creative force and imagination to their own development, for these qualities cannot be taught—they can only be stimulated and appreciated.The School of Art offers an undergraduate art major for students in Yale College (see the bulletin Yale College Programs of Study). In addition, the School’s courses are open to students in the Graduate School of Arts and Sciences and other professional schools of the University, and School of Art students may enroll in elective courses in the Graduate School and other professional schools as well as in the College with permission."
}
